### ISSUE TITLE
Bug Report: wrong plugin name displayed in Homebridge-UI

### ISSUE THREAD

**Issue by jostrasser** [bloomkd46/homebridge-iRobot#107]
### Describe The Bug:

Hi,
only a small cosmetical bug:
After installing 3.0.0-beta, I can see a wrong naming of the plugin in Homebridge-UI:

Should be "Hom**e**bri**d**ge iRobot"

![image](https://user-images.githubusercontent.com/14274103/158527962-cf5b67e2-ae85-42ef-a098-d5b705c431b0.png)

### To Reproduce:

Update to 3.0.0 beta

### Expected behavior:

Correct naming in Homebridge-UI

### Logs:

```shell
N/A
```

### Config:

```shell
N/A
```

### Node Version:

16.14.0

### NPM Version:

8.5.4

### Homebridge Version:

1.4.0

### Plugin Version:

3.0.0-beta15

### Operating System:

Raspberian

**Comment by bloomkd46** [comment]
Thank you for letting me know! I will fix this in the next release

**Comment by jostrasser** [comment]
> Thank you for letting me know! I will fix this in the next release

U´re welcome! :)

**Comment by jostrasser** [comment]
@bloomkd46 https://github.com/bloomkd46/homebridge-iRobot/commit/2614bbfbc4aed84f7de731d518ed6b7a7798584f#commitcomment-68829816
