### ISSUE TITLE
Support Request: some packages are showing as deprecated while installing

### ISSUE THREAD

**Issue by jostrasser** [bloomkd46/homebridge-iRobot#108]
### Describe Your Problem:

Hi,

installed 3.0.0-beta15. While installing I can see that some packages are deprecated or no longer supported:

![image](https://user-images.githubusercontent.com/14274103/158529281-49059750-f287-4e4f-9943-2c8876aab657.png)

How can I solve this?

Thanks!

### Logs:

```shell
See screenshot
```

### Config:

```shell
N/A
```

### Node Version:

16.14.0

### NPM Version:

8.5.4

### Homebridge Version:

1.4.0

### Plugin Version:

3.0.0-beta15

### Operating System:

Raspberian

**Comment by bloomkd46** [comment]
You can ignore these because they will not affect the performance of the plug-in. When you were installing homebridge you should have seen the same thing.

**Comment by jostrasser** [comment]
> You can ignore these because they will not affect the performance of the plug-in. When you were installing homebridge you should have seen the same thing.

okay, thanks!
Do you know, is there a way to solve this or should I ignore it?
I hope I didn't run in a problem related to this in the future.

**Comment by bloomkd46** [comment]
You should ignore it. They are just warnings letting you know that the package is no longer being maintained.

**Comment by jostrasser** [comment]
Okay, thanks for your help!
