### ISSUE TITLE
Bug Report: j7 doesn't display any controls or claim to support room-by-room

### ISSUE THREAD

**Issue by nriley** [bloomkd46/homebridge-iRobot#109]
### Describe The Bug:

I tried installing the beta. I initially had trouble getting it to log into the iRobot site so I manually added it, and I do see a device in HomeKit but can't do anything with it. Also it shows as not supporting room-by-room when it does.

### To Reproduce:

Add a Roomba j7

### Expected behavior:

Something will let me control the vacuum from HomeKit and automatically add switches when I try to clean room-by-room.

Here's what I see in the config UI — looks like it is seeing the vacuum at least but note "false" for "room-by-room support".

![image](https://user-images.githubusercontent.com/68303/159178227-338b0d3a-c088-41f4-98a5-521912985555.png)

And in HomeKit:
<img width="519" alt="j7" src="https://user-images.githubusercontent.com/68303/159178310-52861d44-1b9b-4b50-b092-fe11bafa4280.png">

### Logs:

```shell
[3/20/2022, 2:49:38 PM] ---                                                     
[3/20/2022, 2:49:38 PM] Loaded plugin: homebridge-irobot@3.0.0-beta.16          
[3/20/2022, 2:49:38 PM] Registering platform 'homebridge-irobot.iRobotPlatform' 
[3/20/2022, 2:49:38 PM] ---                                                     
[3/20/2022, 2:49:38 PM] [Roomba] Initializing iRobotPlatform platform...
[3/20/2022, 2:49:40 PM] [Roomba] Succefully logged into iRobot
[3/20/2022, 2:49:45 PM] [Roomba] Adding new accessory: Roomba j7
```

### Config:

```shell
{
            "name": "Roomba",
            "email": "xxx",
            "password": "xxx",
            "manualDiscovery": true,
            "roombas": [
                {
                    "name": "Roomba j7",
                    "blid": "xxx",
                    "password": "xxx",
                    "ip": "172.20.1.99"
                }
            ],
            "lowBattery": 20,
            "offAction": "pause:dock",
            "status": "phase:run",
            "platform": "iRobotPlatform"
        }
```

### Node Version:

v17.7.2

### NPM Version:

8.5.2

### Homebridge Version:

1.4.0

### Plugin Version:

└── homebridge-irobot@3.0.0-beta.16

### Operating System:

MacOS

**Comment by bloomkd46** [comment]
It looks like it is failing to configure your Roomba. Is that IP Address correct? It should be a local IP address which typically follow a 192.168.x.x or 10.0.0.x schema.
The reason it is saying false for room-by-room is due to the fact that I have not yet re-added room-by-room support to the betas

**Comment by bloomkd46** [comment]
PS
After looking closer at your logs it looks like it is logging in to iRobot and fetching Roomba's that way

**Comment by nriley** [comment]
I tried removing `"roombas": [...]` and `manualDiscovery` from the configuration but then I get the following.

```
[3/20/2022, 8:32:55 PM] [Roomba] Failed To Configure Device: {"password":"...","sku":"j755020","softwareVer":"sapphire+1.2.12+Firmwar
e-Production+57","name":"Roomba j7","cap":{"binFullDetect":2,"dockComm":1,"wDevL
oc":2,"bleDevLoc":1,"edge":0,"maps":3,"pmaps":5,"tLine":2,"area":1,"eco":1,"mult
iPass":2,"pose":1,"team":1,"pp":0,"lang":2,"5ghz":1,"prov":3,"sched":1,"svcConf"
:1,"ota":2,"log":2,"langOta":0,"oMode":2,"odoa":2,"expectingUserConf":1},"svcDep
lId":"v007","user_cert":true,"blid":"..."} 
With error: UDP Disabled
[3/20/2022, 8:32:55 PM] [Roomba] UDP Disabled
```

I then tried removing the username/password and I still see the Roomba but still no other accessories other than this one that I can't do anything with:

<img width="110" alt="image" src="https://user-images.githubusercontent.com/68303/159192859-4b534909-19b5-4498-9fa7-9c8e43a28b27.png">

I tried removing the IP address and couldn't get it to work. I am sure the IP address is correct as I had to add its MAC address (and later on, I was only able to ping it after it finished rebooting). My apartment building has building-wide WiFi that I do not control, so I think it may not allow automatic discovery to work.

Eventually I looked at the server process that homebridge-irobot starts and apparently it is looking at the cached accessories.  I had an old workaround (probably no longer necessary, I think I've had it there for 5+ years) that removed the accessories directory every time Homebridge started and I'm guessing this was not helping!  I removed this workaround and now it looks like it's getting further but failing to connect:

```
[3/20/2022, 8:55:51 PM] [Roomba] [Roomba j7] Failed To Auto Update State:
 RequestError: Error: connect ETIMEDOUT 172.20.1.99:443
    at new RequestError (/Users/nicholas/Developer/homebridge/node_modules/reque
st-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/nicholas/Developer/homebridge/node_modu
les/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/nicholas/Developer/homebridge/
node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/nicholas/Developer/homebridge/node_modules/request/
request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.onRequestError (/Users/nicholas/Developer/homebridge/node_modules
/request/request.js:877:8)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  cause: Error: connect ETIMEDOUT 172.20.1.99:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
    errno: -60,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '172.20.1.99',
    port: 443
  },
```

I also tried restarting the Roomba but that didn't help.  Finally, I found https://github.com/koalazak/dorita980/issues/157 so I wonder if this is just a basic problem with the j7(+) and nothing to do with homebridge-iRobot.  I just installed home-assistant as a test and was able to add my j7 to it and control it (but, no room-by-room support so not useful to me), so it seems something wrong with connecting from Homebridge.

Sorry, it was unclear from your changelog whether room-by-room was supported in the beta yet, as you removed this from "TODO" and included such things as "Expect 3.0.0 soon" :-)   I think I will just check back in a few months, so closing this for now.

**Comment by bloomkd46** [comment]
If you are on apartment Wi-Fi then it is probably blocking direct device connections

**Comment by nriley** [comment]
Maybe, though I set up a web server on port 443 and had no trouble connecting to it. Will have to investigate later, spent way too much time on this tonight!
