### ISSUE TITLE
Bug Report: Wiki "Configuration" link gets blocked by GitHub

### ISSUE THREAD

**Issue by ralexmatthews** [bloomkd46/homebridge-iRobot#158]
### Describe The Bug:

When you click on or go directly to the "Configuration" link in the wiki, you get blocked by GitHub saying 

> You do not have permission to update this wiki

<img width="705" alt="Screen Shot 2022-10-10 at 8 47 14 PM" src="https://user-images.githubusercontent.com/31320460/194978941-d57710c9-d85a-4ff1-b5dc-ad89a05b8242.png">

My hunch is that going to https://github.com/bloomkd46/homebridge-iRobot/wiki/Configuration wants to go into a meta "wiki configuration" page, and that other accounts do not have permission for this. I imagine this can be fixed by simply changing the route to something like "homebridge-configuration" or something like that.

### To Reproduce:

1. Log out of GitHub
2. Go to https://github.com/bloomkd46/homebridge-iRobot/wiki/Configuration
3. See that you get redirected to home

**OR**

1. Log into an account other that yours
2. Go to https://github.com/bloomkd46/homebridge-iRobot/wiki/Configuration
3. See the error message posted

### Expected behavior:

See the configuration wiki page

### Logs:

```shell
-
```

### Config:

```shell
-
```

### Node Version:

-

### NPM Version:

-

### Homebridge Version:

-

### Plugin Version:

-

### Operating System:

Other

**Comment by bloomkd46** [comment]
No, this is because their is currently no Configuration Wiki page. I am hoping to add that in the near future

**Comment by ralexmatthews** [comment]
Ah ok. That makes more sense.
