### ISSUE TITLE
s9 - please remove my "i9" previously reported, it's actually an s9 (no such thing as an "i9"!)

### ISSUE THREAD

**Issue by douginoz** [bloomkd46/homebridge-iRobot#161]
### Roomba Model:

s9

### Did It Work

Yes

**Comment by bdsoha** [comment]
@douginoz Can you provide your settings?

**Comment by douginoz** [comment]
Sorry, I deleted the plugin and settings a while ago. The interface is just too cumbersome to use. The native application is superior. I never found a use for having it set up in homebridge.
