### ISSUE TITLE
Support Request: HomeKit automations

### ISSUE THREAD

**Issue by sethhere04** [bloomkd46/homebridge-iRobot#78]
### Describe Your Problem:

How do you go about creating a shortcut or automation in HomeKit once robot is set up?

I tried setting up a shortcut to turn the robot on, turn to manual mode, and then turn on the room. But robot gives error and says map does not match map set in app. They are spelled correctly in both apps. 

### Logs:

```shell
N/A
```

### Config:

```shell
N/A
```

### Node Version:

16.13.2

### NPM Version:

8.3.1

### Homebridge Version:

1.4.0

### Plugin Version:

2.1.16

### Operating System:

Raspberian

**Comment by bloomkd46** [comment]
By shortcut do you mean scene?

**Comment by sethhere04** [comment]
Sorry, I mean in the shortcuts app in iOS. Trying to create a shortcut to vacuum a certain room by giving the command to Siri. I did not try to create a scene first.

**Comment by bloomkd46** [comment]
Try using a scene. Sometimes if the robot gets turned on in manual before the room is turned on it will try to clean a room that doesn't exist

**Comment by sethhere04** [comment]
That seems to work better. Thanks. Still get an error sometimes, but may just be how rooms are being identified in HomeKit.
